// A substring filter for cmdk <Command> lists.
//
// cmdk's default scorer (command-score) matches SUBSEQUENCES, not substrings:
// the query letters only have to appear in order, anywhere. Over a 1,000-name
// employee list that is unusable — "cruz" returns 18 people, none of whom are
// called Cruz, because c-r-u-z can be spelled out of "CAILING, ELMER" and the
// like. Users read the suggestions as simply wrong.
//
// This replaces it with what people actually expect from a name box: every
// whitespace-separated term must appear as a substring, in any order. Order
// independence is what lets "juan dela cruz" find "DELA CRUZ, JUAN" without
// relying on the caller having supplied both name orders as keywords.
//
// Pass it as <Command filter={commandSubstringFilter}>. It cannot be made the
// default inside components/ui/command.tsx — that file is generated by the
// shadcn CLI and must not be hand-edited (see CLAUDE.md).

/**
 * Lowercase, strip accents, and reduce every run of punctuation/whitespace to a
 * single space. Makes "Dela Cruz, Juan", "DELA CRUZ  JUAN" and "dela-cruz juan"
 * all compare equal, so the comma form the trigger button displays matches too.
 */
function normalize(value: string): string {
  return value
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

/**
 * cmdk filter: returns 0 to hide an item, or a positive score used only for
 * ordering. Graded rather than boolean so the closest matches sort to the top —
 * a flat 1/0 would leave results in DOM order, which for the employee pickers
 * is insertion order and looks arbitrary.
 */
export function commandSubstringFilter(
  value: string,
  search: string,
  keywords?: string[],
): number {
  const query = normalize(search);
  if (!query) return 1;

  const haystack = normalize([value, ...(keywords ?? [])].join(" "));
  const terms = query.split(" ").filter(Boolean);

  // Every term must be present. Requiring all of them is what keeps a long
  // query from widening the result set, which is the other half of the
  // subsequence problem: typing more should narrow, never broaden.
  if (!terms.every((t) => haystack.includes(t))) return 0;

  // Rank: whole query as one run beats scattered terms; a match at a word
  // boundary beats one buried mid-word ("cruz" in "Dela Cruz" over "Crux").
  const whole = haystack.includes(query);
  const atBoundary = terms.every(
    (t) => haystack === t || haystack.startsWith(`${t} `) || haystack.includes(` ${t}`),
  );
  if (whole && haystack.startsWith(query)) return 1;
  if (whole) return 0.9;
  if (atBoundary) return 0.8;
  return 0.6;
}
