"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Loader2, Printer, QrCode, RotateCcw } from "lucide-react";
import { toast } from "sonner";
import { pdf } from "@react-pdf/renderer";

import { Button } from "@/components/ui/button";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { QrCardsPdf, cardCode } from "@/components/pdf/qr-cards-pdf";
import {
  issueQrCardForEmployee,
  rotateQrCredential,
  markQrCardsPrinted,
  type EmployeeQrCardState,
} from "@/lib/actions/qr-card-actions";

interface EmployeeQrCardPanelProps {
  employeeId: string;
  state: EmployeeQrCardState;
  /** LGU name, printed across the top of the card exactly as the bulk run prints it. */
  organizationName: string;
}

/**
 * The employee's attendance card, on their own profile.
 *
 * The preview below is the printed card redrawn in HTML — same fields, same
 * 85.6 x 54mm proportions — so what HR sees here is what comes out of the
 * printer. The PDF itself is generated by the same QrCardsPdf component the
 * bulk run at /events/cards uses, with this one card in it.
 */
export function EmployeeQrCardPanel({
  employeeId,
  state,
  organizationName,
}: EmployeeQrCardPanelProps) {
  const router = useRouter();
  const [busy, setBusy] = useState(false);
  const { card } = state;

  const handleIssue = async () => {
    setBusy(true);
    const result = await issueQrCardForEmployee(employeeId);
    setBusy(false);
    if (!result.success) {
      toast.error(result.error);
      return;
    }
    toast.success("Card issued.");
    router.refresh();
  };

  const handlePrint = async () => {
    if (!card) return;
    setBusy(true);
    try {
      const blob = await pdf(
        <QrCardsPdf
          cards={[
            {
              full_name: card.full_name,
              // A temporary card prints the name and the code and nothing else
              // — the same rule the bulk run follows.
              group_name: card.subject_kind === "temporary" ? null : card.group_name,
              employment_label:
                card.subject_kind === "temporary" ? "" : card.employment_label,
              id_number: card.id_number,
              token: card.token,
              qrDataUrl: card.qrDataUrl,
            },
          ]}
          organizationName={organizationName}
        />,
      ).toBlob();
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `qr-card-${card.full_name.replace(/\s+/g, "-").toLowerCase()}.pdf`;
      link.click();
      URL.revokeObjectURL(url);

      // Same stamp the bulk run leaves, so "was this person ever given a card?"
      // stays answerable however the card was produced.
      await markQrCardsPrinted([card.token]);
      toast.success("Card generated.");
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Could not generate the card.");
    }
    setBusy(false);
  };

  const handleReissue = async () => {
    if (!card) return;
    setBusy(true);
    const result = await rotateQrCredential(
      card.subject_kind,
      card.subject_id,
      "Card reissued from employee profile",
    );
    setBusy(false);
    if (!result.success) {
      toast.error(result.error);
      return;
    }
    toast.success("New code issued — the old card no longer scans. Reprint it.");
    router.refresh();
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-base">Attendance QR Card</CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        {card ? (
          <>
            {/* 242.6 x 153.1pt in the PDF — the standard 85.6 x 54mm ID. */}
            <div className="flex aspect-[242.6/153.1] w-full max-w-sm items-center gap-3 rounded-lg border border-dashed bg-white px-3 text-slate-900">
              <div className="min-w-0 flex-1">
                <p className="truncate text-[9px] tracking-[0.08em] text-slate-500">
                  {organizationName.toUpperCase()}
                </p>
                <p className="mt-1 text-sm leading-tight font-bold">
                  {card.full_name}
                </p>
                {card.subject_kind !== "temporary" && card.group_name && (
                  <p className="mt-1 text-[11px] text-slate-700">{card.group_name}</p>
                )}
                {card.subject_kind !== "temporary" && (
                  <p className="mt-1.5 text-[9px] font-bold tracking-[0.05em]">
                    {card.employment_label.toUpperCase()}
                  </p>
                )}
              </div>
              <div className="flex flex-col items-center">
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src={card.qrDataUrl}
                  alt={`Attendance QR code for ${card.full_name}`}
                  className="h-[74px] w-[74px]"
                />
                <span className="mt-0.5 text-[8px] tracking-[0.05em] text-slate-500">
                  {cardCode(card)}
                </span>
              </div>
            </div>

            <p className="text-muted-foreground text-xs">
              The card carries no photo, so whoever holds it scans as this
              person. Reissuing rotates the code and the old card stops working
              at once.
            </p>

            <div className="flex flex-wrap gap-2">
              <Button size="sm" variant="outline" onClick={handlePrint} disabled={busy}>
                {busy ? (
                  <Loader2 className="h-4 w-4 animate-spin" />
                ) : (
                  <Printer className="h-4 w-4" />
                )}
                Print card
              </Button>
              <AlertDialog>
                <AlertDialogTrigger
                  render={<Button size="sm" variant="outline" disabled={busy} />}
                >
                  <RotateCcw className="h-4 w-4" />
                  Reissue
                </AlertDialogTrigger>
                <AlertDialogContent>
                  <AlertDialogHeader>
                    <AlertDialogTitle>Reissue this card?</AlertDialogTitle>
                    <AlertDialogDescription>
                      A new code is minted and the current card stops scanning
                      immediately. Attendance already recorded against the old
                      code is untouched. Print the replacement afterwards.
                    </AlertDialogDescription>
                  </AlertDialogHeader>
                  <AlertDialogFooter>
                    <AlertDialogCancel>Cancel</AlertDialogCancel>
                    <AlertDialogAction onClick={handleReissue}>
                      Reissue
                    </AlertDialogAction>
                  </AlertDialogFooter>
                </AlertDialogContent>
              </AlertDialog>
            </div>
          </>
        ) : (
          <div className="space-y-3">
            <p className="text-muted-foreground text-sm">
              {state.reason ?? "No card has been issued for this employee yet."}
            </p>
            {state.canIssue && (
              <Button size="sm" variant="outline" onClick={handleIssue} disabled={busy}>
                {busy ? (
                  <Loader2 className="h-4 w-4 animate-spin" />
                ) : (
                  <QrCode className="h-4 w-4" />
                )}
                Issue card
              </Button>
            )}
          </div>
        )}
      </CardContent>
    </Card>
  );
}
